steps:
    - name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'bash'
      args:
      - '-c'
      - |
        [[ "$BRANCH_NAME" != "main" ]] && git rebase main || echo fail && true
    
    - name: 'node:20-bullseye'
      entrypoint: npm
      args: ["install"]

    - name: 'node:20-bullseye'
      entrypoint: npm
      args: ["run", "build"]

    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: 'bash'
      args: ['-c', '[[ "$BRANCH_NAME" == "main" ]] && gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy || echo fail && true']
      timeout: '1600s'
options:
    logging: CLOUD_LOGGING_ONLY